const phone = {
  Image: '',
  Brand: '',
  Model: '',
  Announced: '',
  Dimensions: '',
  Display_type: '',
  Display_resolution: '',
  Display_size: '',
  EDGE: '',
  Internal_memory: '',
  Memory_card: '',
  RAM: '',
  Operating_System: '',
  Chipset: '',
  GPU: '',
  CPU: '',
  Battery: '',
  Primary_camera: '',
  Secondary_camera: '',
  Sensors: '',
  Bluetooth: '',
  GPS: '',
  GPRS: '',
  NFC: '',
  WLAN: '',
  Network: '',
  Network_Speed: '',
  SIM: '',
  USB: '',
  Radio: '',
  Loud_speaker: '',
  Audio_jack: '',
  FourG: '',
  ThreeG: '',
  TwoG: '',
  Status: '',
  Colors: ''
}

export default phone;